name: matrix 
on:
  push:
    branches:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20, 22]
        browser: [chrome, firefox, safari]
    steps:
      - name: Print Node Version and Browser
        run: echo "${{matrix.node}} - ${{matrix.browser}}"