name: Deploy React CSR
on: 
  push:
    branches:
      - main
  
  workflow_dispatch:
  pull_request:
    types:
      - opened
jobs:
  lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v5
        - name: Setup Node.js
          uses: actions/setup-node@v5
          with:
            node-version: 22
        - run: npm install
        - name: Run lint 
          run: npm run lint

  deploy:
      needs: lint
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v5
        - name: Setup Node.js
          uses: actions/setup-node@v5
          with:
            node-version: 22
        - run: npm install
        - run: npm run build
        - name: Deploy to GitHub Pages
          run: echo "Deploying to GitHub Pages."
